### ISSUE TITLE
Create transaction from binary payload

### ISSUE THREAD

**Issue by fullcircle23** [nemtech/nem2-sdk-java#123]
Created new issue for the below function originally reported in #57 

<table>
  <tr>
   <td><strong>Function</strong>
   </td>
   <td><strong>Description</strong>
   </td>
  </tr>
  <tr>
   <td>createFromPayload(data:string):Transaction
   </td>
   <td>Reads the unsigned payload and creates a Transaction.
   </td>
  </tr>
</table>

**Comment by fboucquez** [comment]
Fixed in 0.14.0
