### ISSUE TITLE
Implement new 'Mosaic Owned' endpoints 

### ISSUE THREAD

**Issue by fboucquez** [nemtech/nem2-sdk-java#124]
As new endpoints will be introduced in catapult-rest and OpenAPI v0.7.19. 

https://github.com/nemtech/nem2-openapi/pull/32

**Comment by dgarcia360** [comment]
Note that this endpoint is not implemented in REST and the API contract could be modified.

**Comment by fboucquez** [comment]
Hi @Vektrat @dgarcia360. Has mosaic owned been fully implemented in rest and open API? Can we unblock this issue?

**Comment by Vektrat** [comment]
it's implemented at REST side
