### ISSUE TITLE
Metadata and Mosaic Restriction transactions do not support aliased mosaics

### ISSUE THREAD

**Issue by rg911** [nemtech/nem2-sdk-java#131]
The serialization schemas define that the next fields can be aliased.

* https://github.com/nemtech/catbuffer/blob/master/schemas/metadata/mosaic_metadata.cats#L12
* https://github.com/nemtech/catbuffer/blob/master/schemas/restriction_mosaic/mosaic_address_restriction.cats#L6
* https://github.com/nemtech/catbuffer/blob/master/schemas/restriction_mosaic/mosaic_global_restriction.cats#L7-10

The NEM2-SDK should accept ``NamespaceId`` for these fields as well as the current ``MosaicId`` type.

**Comment by fboucquez** [comment]
Fixed in 0.14.0
