### ISSUE TITLE
Top Level serialize() doesn't include Signature and Signer

### ISSUE THREAD

**Issue by fboucquez** [nemtech/nem2-sdk-java#135]
At the moment, in Java and TS sdks, the top-level transaction Signature and Signer fields are not being serialized as they are not part of the top-level Transaction Objects (they are part of the SignedTransaction creating during the signWith).

This issue needs further discussion as both SDKs would need to be updated at the same time. TS and Java should be able to read and write the same format. 

Note that the signer is serialized as part of the embedded/inner transaction

**Comment by fullcircle23** [comment]
Hi @fboucquez The serialization seems to be happening here
https://github.com/nemtech/nem2-sdk-java/blob/ccdf9917579e60782f512ce474a133aa0dd08175/sdk-core/src/main/java/io/nem/sdk/model/transaction/Transaction.java#L190

**Comment by fboucquez** [comment]
Fixed
