### ISSUE TITLE
The network type is hardcoded in the fromUnresolvedAddressToByteBuffer

### ISSUE THREAD

**Issue by Wayonb** [nemtech/nem2-sdk-java#140]
1. Expected behavior and actual behavior.
Submitting an alias transfer failed on the public test network and expect the transfer to succeed. 
2. Steps to reproduce the problem.
Submitting an alias transfer on the public test network.
This line 
            final byte firstByte = (byte) 0x91;
should be 
            final byte firstByte = (byte) (networkType | 0x01);
https://github.com/nemtech/nem2-sdk-java/blob/058489c4ef932500d63b10833f672ebbcef4d4d6/sdk-core/src/main/java/io/nem/sdk/infrastructure/SerializationUtils.java#L134

**Comment by fboucquez** [comment]
Fixed
