### ISSUE TITLE
The default network currency for the blockchain is "cat.currency" and cannot be updated.

### ISSUE THREAD

**Issue by Wayonb** [nemtech/nem2-sdk-java#148]
In one of our current test environment the default network currency is "nem.xem" instead of "cat.currency".  This makes the NetworkCurrencyMosaic class incorrect to use.  
Currently the default currency alias is not stored in the blockchain but either way the NetworkCurrencyMosaic class needs to be configurable to allow the app to specify the currency namespace name.
https://github.com/nemtech/nem2-sdk-java/blob/9154b337905618d0df481ac1d07e1c04c38412e5/sdk-core/src/main/java/io/nem/sdk/model/mosaic/NetworkCurrencyMosaic.java#L20

**Comment by fboucquez** [comment]
Is it possible to load the configured currency name from an endpoint? It's
better if we can resolve that value without SDK devs needing to set up a
configuration file.

**Comment by Wayonb** [comment]
I agree that the an endpoint would be ideal but you would need to talk to Rest devs about it.  In either case I open the bug here since there would be some work on the SDK.

@dgarcia360 Any suggestion on this?

**Comment by dgarcia360** [comment]
In nem-library (NIS1), we used [the class XEM](https://github.com/NemProject/nem-library-ts/blob/master/src/models/asset/XEM.ts) to provide quick access to the **public** network currency mosaic. In the future, we might want to rename ``NetworkCurrencyMosaic`` to ``XEM``, or use the name of the ticker once it's decided how it is going to be named.

 Take into account that the SDK should be able to work with multiple networks at the same time, so overriding on startup the ``NetworkCurrencyMosaic`` class could become problematic.

To work with other networks currency mosaics, currently devs have the following options:

a. Use aliases:

`` [new Mosaic(new NamespaceId('custom'), UInt64.fromUint(1000))]``

b. Adapt the [NetworkCurrencyMosaic](https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/master/src/model/mosaic/NetworkCurrencyMosaic.ts ), setting their mosaic definition.

c. Get the MosaicView using [mosaicsView(mosaicIds: MosaicId[])](https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/56fbd0260926ab954b716add0a45c182e01632e7/src/service/MosaicService.ts#L48)  (requires internet connection), and then create a mosaic.

The problem with solutions a and b is that we need to get its divisibility first before we can announce a transaction. The **third solution (c) looks ideal**, but requires to be a bit enhanced to become more usable:

* The ``MosaicService.mosaicsView(mosaicIds: MosaicId[])`` function should support aliases (NamespaceId) as well.
* The [MosaicView](https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/master/src/service/MosaicView.ts) class could provide the functions ``createRelative`` and ``createAbsolute``, returning a Mosaic object.

Let me know what do you think about the solution proposed, and do not hesitate to propose other suggestions.

**Comment by fboucquez** [comment]
Hi @Wayonb 

If you like I can provide constructor/create methods that allow users to use a custom NamespaceId, for example 

```
NetworkCurrencyMosaic.createRelative(new NamespaceId("nem.xem"), BigInteger.valueOf(1000))
```
https://github.com/nemtech/nem2-sdk-java/blob/master/sdk-core/src/main/java/io/nem/sdk/model/mosaic/NetworkCurrencyMosaic.java#L41

Is this good enough?

**Comment by Wayonb** [comment]
Hi @dgarcia360,
NetworkCurrencyMosaic is a generic name which currently seems it represent the default currency for the catapult public network.  Probably make sense to rename it since only representing the public chain currency.

How does the current Wallet works with multiple catapult networks if they have different currency?  Does the user have to enter the namespace name when switch?  Ideally it would be good for each API/Rest node to be able to report its default currency.

Option c) seems like a good option since most transactions should take UnresolvedMosaicId and internet connection should not be needed.  The only think which will not work is createRelative() as you mention which should fail if divisibility is unknown.

**Comment by fboucquez** [comment]
Java doesn't have the MosaicService, it does have the "low level" MosaicRepositry that give you the mosaic Infos (pretty much the same information, the service just delegate and maps.) We could add the createRelative, createAbsolute methods in MosaicInfo if you like

The SDK client developer can subclass Mosaic like NetworkCurrencyMosaic/NetworkHarvestMosaic and create different currency for different networks. Then select the right mosaic when calling a given network (public, private, etc.).

Java SDK clients can do anything as is. We could have some features to simplify the process but nothing seems too hard.
