### ISSUE TITLE
Transaction classes should have a size method.

### ISSUE THREAD

**Issue by Wayonb** [nemtech/nem2-sdk-java#149]
The transaction size is used to calculate the transaction fee.  It would be good for the user to know tx size so that a correct maxFee can be use in the transaction.  

See TS class - 
https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/9bae277b97be7de3e6667d07165f89856d3bdb96/src/model/transaction/AggregateTransaction.ts#L273

**Comment by fboucquez** [comment]
Fixed in master
