### ISSUE TITLE
Update DTOs

### ISSUE THREAD

**Issue by alexjavabraz** [nemtech/nem2-sdk-java#16]
Generate and integrate new DTOs with [Swagger CodeGen](https://swagger.io/tools/swagger-codegen/).

The new API definition can be found [here](https://github.com/nemtech/nem2-docs/blob/master/source/resources/collections/swagger.yaml).

Example of generated DTOs [here](https://github.com/nemtech/nem2-sdk-java/tree/master/src/main/java/io/nem/sdk/model)

**Comment by alexjavabraz** [comment]
Working on it

**Comment by fullcircle23** [comment]
@alexjavabraz I've created sub-feature branch _**cow-base/dto**_ from feature branch _cow-base/master_. Please checkout and push the DTO updates to cow-base/dto. As discussed earlier, make your changes in the existing packages. So all swagger generated code will be in _infrastructure_ package and other changes will be in the respective classes packages. Thanks.

**Comment by fullcircle23** [comment]
@alexjavabraz I just noticed that you've used BigInteger & UInt64 instead of UInt64DTO in the DTOs. Any reason for this?

**Comment by fullcircle23** [comment]
@alexjavabraz There's been some changes in swagger.yaml. Could you include those changes as well?

**Comment by alexjavabraz** [comment]
@fullcircle23 i generated new DTOs based on swagger.yml updates. The class UInt64DTO was updated.

**Comment by fullcircle23** [comment]
@alexjavabraz Good job! However, it appears that you're not using the latest version of swagger.yaml from  https://github.com/nemtech/nem2-docs/blob/master/source/resources/collections/swagger.yaml.
In the latest swagger.yaml, `NamespaceMosaicMetaDTO` has been replaced by `NamespaceMetaDTO` and `MosaicMetaDTO` which was not reflected in your DTOs. There have also been several other changes in the last 2 months. Please ensure all changes have been incorporated. Many thanks.

**Comment by alexjavabraz** [comment]
@fullcircle23 i used that url: [https://nemtech.github.io/_downloads/swagger.yaml](https://nemtech.github.io/_downloads/swagger.yaml)

**Comment by fullcircle23** [comment]
@alexjavabraz with the frequent revisions in swagger.yaml, the copy at https://nemtech.github.io/_downloads/swagger.yaml is out of sync. Please use the one in nem2-docs repo: https://github.com/nemtech/nem2-docs/blob/master/source/resources/collections/swagger.yaml.

**Comment by fullcircle23** [comment]
Updated DTOs in cow-base/master
