### ISSUE TITLE
Unmappable character for encoding ASCII

### ISSUE THREAD

**Issue by fajarvm** [nemtech/nem2-sdk-java#162]
This might be a common issue for most Java projects, but I thought it might be useful to leave an issue here.

**Problem**
The project won't compile due to error "Unmappable character for encoding ASCII" which points to some special characters in the source code. 

**Steps to reproduce**
Execute command: `gradle clean build`
Or any of the compile tasks, for that matter.

**Solution / workaround:**
Set the default file encoding to UTF8. This can be done by setting it as a global environment variable, or scoped to this specific project (via IDE).

Add an environment variable:
```
export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
```

**Comment by fboucquez** [comment]
Hi @fajarvm,

We have added the UTF-8 encoding to the Gradle build. Thanks for reporting the issue

Fernando
