### ISSUE TITLE
BalanceTransferReceipt not serialized correctly  

### ISSUE THREAD

**Issue by fboucquez** [nemtech/nem2-sdk-java#177]
Discussion https://nem2.slack.com/archives/CEZKUE4KB/p1575984574342700

https://github.com/nemtech/catbuffer/blob/659e4924e0faee323f6b9c6b26fe74047bd60e8b/schemas/receipts.cats#L19

Implementations:

https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/master/src/model/receipt/BalanceTransferReceipt.ts#L72

https://github.com/nemtech/nem2-sdk-java/blob/master/sdk-core/src/main/java/io/nem/sdk/model/receipt/BalanceTransferReceipt.java#L131

**Comment by rg911** [comment]
basically just need to reorder fields in the buffer generation to mach definition on catbuffer
