### ISSUE TITLE
Mosaic / Namespace split and Alias enhancement

### ISSUE THREAD

**Issue by fullcircle23** [nemtech/nem2-sdk-java#18]
[Catapult Server Mosaics Changelog](https://github.com/nemtech/catapult-server/blob/master/CHANGELOG.md#changed) : Mosaics are no longer tied to namespaces. This means a mosaic is no longer identified by the namespace. Instead, the identifier is a random uint64.

### Fix models and unit tests - remove/adapt all direct/indirect associations between namespaces and mosaics in these classes: ###

Key changes / additions:

io.nem.sdk.infrastructure
- [x] MosaicRepository
- [x] MosaicHttp*
- [x] NamespaceHttp*
- [x] TransactionMappingTest

io.nem.sdk.model.transaction
- [x] IdGenerator
  - [x] IdGeneratorTest
- [x] UInt64
  - [x] UInt64Test
- [x] UInt64Id
- [x] TransactionVersion
- [x] MosaicDefinitionTransactionTest*
- [x] RegisterNamespaceTransactionTest*

io.nem.sdk.model.account
- [x] AccountInfoTest

_io.nem.sdk.model.mosaic_
- [x] Mosaic
  - [x] MosaicTest
- [x] MosaicId
  - [x] MosaicIdTest
- [x] MosaicInfo
  - [x] MosaicInfoTest
- [x] MosaicNonce
  - [x] MosaicNonceTest
- [x] NetworkCurrencyMosaic
  - [x] NetworkCurrencyMosaicTest
- [x] NetworkHarvestMosaic
  - [x] NetworkHarvestMosaicTest

_io.nem.sdk.model.namespace_
- [x] NamespaceId
  - [x] NamespaceIdTest
- [x] Alias
  - [x] AliasTest
- [x] AliasType
- [x] AliasAction
- [x] EmptyAlias
- [x] MosaicAlias
- [x] AddressAlias

io.nem.core.utils
- [x] ByteUtils
  - [x] ByteUtilsTest

* Partially complete - pending DTO and catbuffer integration.
Also, integration tests such as MosaicHttpTest and NamespaceHttpTest that fail in bison/cow to be fixed after DTO/catbuffer integration.

### References & Related Changes ###
1. [Catapult Server Mosaics Changelog](https://github.com/nemtech/catapult-server/blob/master/CHANGELOG.md#changed)
2. [Mosaic / Namespace Split in Typescript SDK](https://github.com/nemtech/nem2-sdk-typescript-javascript/issues/48)

**Comment by fullcircle23** [comment]
I'll be working on these changes.

**Comment by alexjavabraz** [comment]
Openede PR #23
