### ISSUE TITLE
Change secretlock sha512 to sha256

### ISSUE THREAD

**Issue by sleepyOwl14** [nemtech/nem2-sdk-java#19]
Catapult native for cross-chain swaps will be sha3 256 instead of sha3 512.

**Comment by sleepyOwl14** [comment]
I'll be working on this.

**Comment by fullcircle23** [comment]
@sleepyOwl14  Could you update the unit tests for these in accordance with the updated transaction types?

**Comment by sleepyOwl14** [comment]
New PR [#32](https://github.com/nemtech/nem2-sdk-java/pull/32) have been created for this

thanks
