### ISSUE TITLE
SDK status is not throwing errors

### ISSUE THREAD

**Issue by ugniusvers** [nemtech/nem2-sdk-java#194]
After announcing a transaction a status is expected to throw an error if there is any. This was happening in previous versions of nem2-sdk.

This was fixed in nem2-sdk-typescript-javascript, must be checked in java too.

https://github.com/nemtech/nem2-sdk-typescript-javascript/issues/411
https://github.com/nemtech/catapult-rest/commit/1cf85eba81aea8f74cab0382520c7a48a9830e30

**Comment by fboucquez** [comment]
Fixed
