### ISSUE TITLE
New lock hash algorithms for secret lock

### ISSUE THREAD

**Issue by sleepyOwl14** [nemtech/nem2-sdk-java#20]
Add new lock hash algorithms for secret lock transaction [nemtech/catapult-server#13](https://github.com/nemtech/catapult-server/issues/13)

**Comment by sleepyOwl14** [comment]
This is also with me

**Comment by fullcircle23** [comment]
@sleepyOwl14  Could you update the unit tests for these in accordance with the updated transaction types?

**Comment by sleepyOwl14** [comment]
New PR #32 have been created for this

thanks
