### ISSUE TITLE
Update RolesTypeEnum according to the open api

### ISSUE THREAD

**Issue by fboucquez** [nemtech/nem2-sdk-java#210]
https://github.com/nemtech/nem2-openapi/pull/69

**Comment by Wayonb** [comment]
@fboucquez When do you plan to release this support?  I need to run some tests on a dual node.

**Comment by fboucquez** [comment]
Once PR has been merged I'll release

**Comment by fboucquez** [comment]
@Wayonb 

Every time there is a merge to master, Travis pushes a snapshot version to maven central automatically.

https://oss.sonatype.org/content/repositories/snapshots/io/nem/sdk-vertx-client/0.16.4-SNAPSHOT/

So if you are in a rush, you can always have the latest SNAPSHOT version in your app and then change to the release version once we do it (it will be 0.16.4).
