### ISSUE TITLE
Unable to open the listener

### ISSUE THREAD

**Issue by Wayonb** [nemtech/nem2-sdk-java#219]
Trying to open a listener connection to the rest gateway and the web socket handler is failing in the toJsonObject() call.  Not sure if I am missing something.

code sample:
	Listener listener = getRepositoryFactory().createListener();
	listener.open().get();

Exception in the handler.toJsonObject():
        httpClient.websocket(
            requestOptions,
            ws -> {
                this.webSocket = ws;
                ws.handler(
                    handler -> {
                        ObjectNode message = getJsonHelper()
                            .convert(handler.toJsonObject(), ObjectNode.class);
                        handle(message, future);
                    });
            });

handler = {"uid": "XX2HPRENWUY7GVVWGACW3S2QIMFQ57O3"}

Feb 11, 2020 3:52:24 PM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.ObjectMapper.readValue(Ljava/io/DataInput;Ljava/lang/Class;)Ljava/lang/Object;
	at io.vertx.core.json.Json.decodeValue(Json.java:170)
	at io.vertx.core.json.JsonObject.fromBuffer(JsonObject.java:958)
	at io.vertx.core.json.JsonObject.<init>(JsonObject.java:78)
	at io.vertx.core.buffer.impl.BufferImpl.toJsonObject(BufferImpl.java:82)
	at io.nem.sdk.infrastructure.vertx.ListenerVertx.lambda$null$0(ListenerVertx.java:92)
	at io.vertx.core.http.impl.WebSocketImplBase.handleFrame(WebSocketImplBase.java:262)
	at io.vertx.core.http.impl.ClientConnection.handleWsFrame(ClientConnection.java:397)
	at io.vertx.core.http.impl.ClientHandler.handleMessage(ClientHandler.java:111)
	at io.vertx.core.http.impl.ClientHandler.handleMessage(ClientHandler.java:36)
	at io.vertx.core.net.impl.VertxHandler.lambda$channelRead$1(VertxHandler.java:150)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:342)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:200)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:148)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by fboucquez** [comment]
You may have version conflicts of Jackson libraries? can you resolve the list using MVN or a Gradle?
What's your project/branch?

**Comment by Wayonb** [comment]
Below is the dependency tree.  Looks like the api-vertx-client depends on an older version of Jackson.

I will update my dependencies tomorrow and see if that helps.

[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ integrationtests ---
[INFO] io.nem:integrationtests:jar:0.9.2.1
[INFO] +- io.cucumber:cucumber-java:jar:2.3.1:test
[INFO] |  \- io.cucumber:cucumber-core:jar:2.3.1:test
[INFO] |     +- io.cucumber:cucumber-jvm-deps:jar:1.0.6:test
[INFO] |     +- io.cucumber:gherkin:jar:5.0.0:test
[INFO] |     \- io.cucumber:tag-expressions:jar:1.1.1:test
[INFO] +- io.cucumber:cucumber-junit:jar:2.3.1:test
[INFO] +- junit:junit:jar:4.12:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- info.cukes:cucumber-junit:jar:1.2.5:test
[INFO] +- info.cukes:cucumber-java:jar:1.2.5:compile
[INFO] +- info.cukes:cucumber-core:jar:1.2.5:compile
[INFO] |  +- info.cukes:cucumber-html:jar:0.2.3:compile
[INFO] |  \- info.cukes:cucumber-jvm-deps:jar:1.0.5:compile
[INFO] +- info.cukes:cucumber-picocontainer:jar:1.2.5:test
[INFO] |  \- org.picocontainer:picocontainer:jar:2.15:test
[INFO] +- info.cukes:gherkin:jar:2.12.2:provided
[INFO] +- io.nem:sdk-vertx-client:jar:0.16.3:compile
[INFO] |  +- io.nem:sdk-core:jar:0.16.3:compile
[INFO] |  |  +- io.nem:catbuffer:jar:2.0.1:compile
[INFO] |  |  +- org.bouncycastle:bcprov-jdk15on:jar:1.58:compile
[INFO] |  |  +- commons-codec:commons-codec:jar:1.11:compile
[INFO] |  |  +- org.apache.commons:commons-lang3:jar:3.9:compile
[INFO] |  |  +- org.apache.commons:commons-math3:jar:3.2:compile
[INFO] |  |  \- com.googlecode.javaewah:JavaEWAH:jar:1.0.0:compile
[INFO] |  +- io.nem:api-vertx-client:jar:0.7.20.7:compile
[INFO] |  |  +- javax.annotation:javax.annotation-api:jar:1.3.2:compile
[INFO] |  |  +- io.swagger:swagger-annotations:jar:1.5.21:compile
[INFO] |  |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |  |  +- io.vertx:vertx-web-client:jar:3.4.2:compile
[INFO] |  |  |  \- io.vertx:vertx-web-common:jar:3.4.2:compile
[INFO] |  |  +- io.vertx:vertx-rx-java:jar:3.4.2:compile
[INFO] |  |  |  \- io.reactivex:rxjava:jar:1.3.0:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-core:jar:2.6.4:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.6.4:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.6.4:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.6.4:compile
[INFO] |  |  \- com.github.joschi.jackson:jackson-datatype-threetenbp:jar:2.6.4:compile
[INFO] |  |     \- org.threeten:threetenbp:jar:1.3.1:compile
[INFO] |  \- io.vertx:vertx-rx-java2:jar:3.5.0:compile
[INFO] |     \- io.vertx:vertx-core:jar:3.5.0:compile
[INFO] |        +- io.netty:netty-common:jar:4.1.15.Final:compile
[INFO] |        +- io.netty:netty-buffer:jar:4.1.15.Final:compile
[INFO] |        +- io.netty:netty-transport:jar:4.1.15.Final:compile
[INFO] |        +- io.netty:netty-handler:jar:4.1.15.Final:compile
[INFO] |        |  \- io.netty:netty-codec:jar:4.1.15.Final:compile
[INFO] |        +- io.netty:netty-handler-proxy:jar:4.1.15.Final:compile
[INFO] |        |  \- io.netty:netty-codec-socks:jar:4.1.15.Final:compile
[INFO] |        +- io.netty:netty-codec-http:jar:4.1.15.Final:compile
[INFO] |        +- io.netty:netty-codec-http2:jar:4.1.15.Final:compile
[INFO] |        +- io.netty:netty-resolver:jar:4.1.15.Final:compile
[INFO] |        \- io.netty:netty-resolver-dns:jar:4.1.15.Final:compile
[INFO] |           \- io.netty:netty-codec-dns:jar:4.1.15.Final:compile
[INFO] +- org.zeromq:jeromq:jar:0.5.1:compile
[INFO] |  \- eu.neilalexander:jnacl:jar:1.0.0:compile
[INFO] +- org.mongodb:mongo-java-driver:jar:3.10.1:compile
[INFO] +- org.mongodb:bson:jar:2.13.3:compile
[INFO] +- io.reactivex.rxjava2:rxjava:jar:2.1.7:compile
[INFO] |  \- org.reactivestreams:reactive-streams:jar:1.0.1:compile
[INFO] +- org.apache.maven.plugins:maven-pmd-plugin:maven-plugin:3.12.0:compile
[INFO] |  +- org.apache.maven:maven-artifact:jar:3.0:compile
[INFO] |  +- org.apache.maven:maven-model:jar:3.0:compile
[INFO] |  +- org.apache.maven:maven-plugin-api:jar:3.0:compile
[INFO] |  |  \- org.sonatype.sisu:sisu-inject-plexus:jar:1.4.2:compile
[INFO] |  |     +- org.codehaus.plexus:plexus-classworlds:jar:2.2.3:compile
[INFO] |  |     \- org.sonatype.sisu:sisu-inject-bean:jar:1.4.2:compile
[INFO] |  |        \- org.sonatype.sisu:sisu-guice:jar:noaop:2.1.7:compile
[INFO] |  +- org.apache.maven.shared:maven-artifact-transfer:jar:0.10.0:compile
[INFO] |  |  +- org.apache.maven:maven-core:jar:3.0:compile
[INFO] |  |  |  +- org.apache.maven:maven-settings:jar:3.0:compile
[INFO] |  |  |  +- org.apache.maven:maven-settings-builder:jar:3.0:compile
[INFO] |  |  |  +- org.apache.maven:maven-repository-metadata:jar:3.0:compile
[INFO] |  |  |  +- org.apache.maven:maven-model-builder:jar:3.0:compile
[INFO] |  |  |  +- org.apache.maven:maven-aether-provider:jar:3.0:runtime
[INFO] |  |  |  +- org.sonatype.aether:aether-impl:jar:1.7:compile
[INFO] |  |  |  |  \- org.sonatype.aether:aether-spi:jar:1.7:compile
[INFO] |  |  |  +- org.sonatype.aether:aether-api:jar:1.7:compile
[INFO] |  |  |  +- org.sonatype.aether:aether-util:jar:1.7:compile
[INFO] |  |  |  +- org.codehaus.plexus:plexus-interpolation:jar:1.14:compile
[INFO] |  |  |  \- org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3:compile
[INFO] |  |  |     \- org.sonatype.plexus:plexus-cipher:jar:1.4:compile
[INFO] |  |  +- org.codehaus.plexus:plexus-component-annotations:jar:1.7.1:compile
[INFO] |  |  +- org.apache.maven.shared:maven-common-artifact-filters:jar:3.0.1:compile
[INFO] |  |  \- org.slf4j:slf4j-api:jar:1.7.5:compile
[INFO] |  +- net.sourceforge.pmd:pmd-core:jar:6.13.0:compile
[INFO] |  |  +- org.antlr:antlr4-runtime:jar:4.7:compile
[INFO] |  |  +- com.beust:jcommander:jar:1.72:compile
[INFO] |  |  +- net.java.dev.javacc:javacc:jar:5.0:compile
[INFO] |  |  +- net.sourceforge.saxon:saxon:jar:9.1.0.8:compile
[INFO] |  |  +- org.ow2.asm:asm:jar:7.1:compile
[INFO] |  |  +- com.google.code.gson:gson:jar:2.8.5:compile
[INFO] |  |  \- net.sourceforge.saxon:saxon:jar:dom:9.1.0.8:runtime
[INFO] |  +- net.sourceforge.pmd:pmd-java:jar:6.13.0:compile
[INFO] |  +- net.sourceforge.pmd:pmd-javascript:jar:6.13.0:compile
[INFO] |  |  \- org.mozilla:rhino:jar:1.7.7.2:compile
[INFO] |  +- net.sourceforge.pmd:pmd-jsp:jar:6.13.0:compile
[INFO] |  +- org.slf4j:jul-to-slf4j:jar:1.7.25:compile
[INFO] |  +- org.apache.maven.doxia:doxia-sink-api:jar:1.7:compile
[INFO] |  |  \- org.apache.maven.doxia:doxia-logging-api:jar:1.7:compile
[INFO] |  +- org.apache.maven.doxia:doxia-decoration-model:jar:1.7:compile
[INFO] |  +- org.apache.maven.doxia:doxia-site-renderer:jar:1.7:compile
[INFO] |  |  +- org.apache.maven.doxia:doxia-core:jar:1.7:compile
[INFO] |  |  |  +- commons-lang:commons-lang:jar:2.4:compile
[INFO] |  |  |  \- xmlunit:xmlunit:jar:1.5:compile
[INFO] |  |  +- org.apache.maven.doxia:doxia-skin-model:jar:1.7:compile
[INFO] |  |  +- org.apache.maven.doxia:doxia-module-xhtml:jar:1.7:compile
[INFO] |  |  +- org.apache.maven.doxia:doxia-module-fml:jar:1.7:compile
[INFO] |  |  +- org.codehaus.plexus:plexus-i18n:jar:1.0-beta-7:compile
[INFO] |  |  +- org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-30:compile
[INFO] |  |  +- org.codehaus.plexus:plexus-velocity:jar:1.1.7:compile
[INFO] |  |  +- org.apache.velocity:velocity:jar:1.7:compile
[INFO] |  |  +- org.apache.velocity:velocity-tools:jar:2.0:compile
[INFO] |  |  |  +- commons-beanutils:commons-beanutils:jar:1.7.0:compile
[INFO] |  |  |  +- commons-digester:commons-digester:jar:1.8:compile
[INFO] |  |  |  +- commons-chain:commons-chain:jar:1.1:compile
[INFO] |  |  |  +- commons-validator:commons-validator:jar:1.3.1:compile
[INFO] |  |  |  +- dom4j:dom4j:jar:1.1:compile
[INFO] |  |  |  +- oro:oro:jar:2.0.8:compile
[INFO] |  |  |  +- sslext:sslext:jar:1.2-0:compile
[INFO] |  |  |  +- org.apache.struts:struts-core:jar:1.3.8:compile
[INFO] |  |  |  |  \- antlr:antlr:jar:2.7.2:compile
[INFO] |  |  |  +- org.apache.struts:struts-taglib:jar:1.3.8:compile
[INFO] |  |  |  \- org.apache.struts:struts-tiles:jar:1.3.8:compile
[INFO] |  |  \- commons-collections:commons-collections:jar:3.2.1:compile
[INFO] |  +- org.apache.maven.reporting:maven-reporting-api:jar:3.0:compile
[INFO] |  +- org.apache.maven.reporting:maven-reporting-impl:jar:3.0.0:compile
[INFO] |  |  \- org.apache.maven.shared:maven-shared-utils:jar:3.2.0:compile
[INFO] |  +- org.codehaus.plexus:plexus-resources:jar:1.0.1:compile
[INFO] |  +- org.codehaus.plexus:plexus-utils:jar:3.0.24:compile
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.5.3:compile
[INFO] |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.6:compile
[INFO] |  |  \- commons-logging:commons-logging:jar:1.2:compile
[INFO] |  \- commons-io:commons-io:jar:2.5:compile
[INFO] +- org.hamcrest:hamcrest:jar:2.1:test
[INFO] +- org.rocksdb:rocksdbjni:jar:6.5.3:compile
[INFO] +- org.apache.logging.log4j:log4j-api:jar:2.13.0:compile
[INFO] +- org.apache.logging.log4j:log4j-core:jar:2.13.0:compile
[INFO] \- org.apache.logging.log4j:log4j-jul:jar:2.13.0:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.370 s
[INFO] Finished at: 2020-02-11T23:46:02-05:00
[INFO] ------------------------------------------------------------------------
Wayons-MacBook-Pro:integrationtests tbdev$
