### ISSUE TITLE
generateBytes() method does not include transaction fee

### ISSUE THREAD

**Issue by Wondertan** [nemtech/nem2-sdk-java#22]
The code below is presented in every transaction type `generateBytes()` implementation, so transaction fees are always omitted and never included in transaction.

```java
int[] fee = new int[]{0, 0};
int feeVector = SecretLockTransactionBuffer.createFeeVector(builder, fee);
SecretLockTransactionBuffer.addFee(builder, feeVector);
```
This works on test networks where harvesters generate blocks without getting any incentives for their work, but in production the sdk is considered broken.

I also suggest to add the test case for fees in serialization related tests.

**Comment by fullcircle23** [comment]
Hi @Wondertan, thanks for raising this issue. This is already being addressed as the current serialization/deserialization code is being replaced by base code generated by [nemtech/catbuffer](https://github.com/nemtech/catbuffer) where the fee is not fixed to 0 but obtained from the transaction. @Wayonb, @st-wong - please note suggestion to add test case for fees in serialization related tests.
