### ISSUE TITLE
Campatibility with `symbol-testnet-bootstrap v.0.9.2.1`

### ISSUE THREAD

**Issue by petrkir** [nemtech/nem2-sdk-java#221]
There are problems with `symbol-testnet-bootstrap` v.0.9.2.1 (https://github.com/nemfoundation/symbol-testnet-bootstrap) because sdk uses version 0.7.20.7 of `io.nem:api-okhttp-gson-client` and `io.nem:api-vertx-client`.

If possible, please tell more information about campatibility between sdk and `symbol-testnet-bootstrap` vesions and when it will be possible to use sdk for testing with current `symbol-testnet-bootstrap` vesions?

**Comment by fboucquez** [comment]
Hi @petrkir 

What are the current problems you are seeing? 

The latest SDK snapshot 0.16.4-SNAPSHOT is compatible with open API 0.8.3. Do you want to try that one? We will be releasing 0.16.4 soon.

I need some digging about which version of the Open API current rest on [symbol-testnet-bootstrap](https://github.com/nemfoundation/symbol-testnet-bootstrap) is compatibly

**Comment by petrkir** [comment]
Yes, everything will work fine with new version of the API. 
Thank you for reply
