### ISSUE TITLE
WS listener.status return high deadline value

### ISSUE THREAD

**Issue by rg911** [nemtech/nem2-sdk-java#229]
When the transaction announcement failed, ws message (status channel) returns a very high deadline value `9242230873179291650` even though the deadline used in the tx is only for 2 hours

**Comment by fboucquez** [comment]
I think code and deadline lines need to be swapped in rest

https://github.com/nemtech/catapult-rest/blob/master/rest/src/connection/MessageChannelBuilder.js#L96

Reflecting this server change:

https://github.com/nemtech/catapult-server/commit/bc4185117de1bf2c15d9797aec7c57f20175b7f2
