### ISSUE TITLE
Removal of hashing function in the latest snapshot.

### ISSUE THREAD

**Issue by Wayonb** [nemtech/nem2-sdk-java#231]
In latest checkin the following functions were remove:
Hashes.keccak256()
Hashes.hash160()

These methods were still use for secret lock transactions.  Is there another option?

**Comment by fboucquez** [comment]
I removed them for code cleanup. I'll put them back if they are used

**Comment by fboucquez** [comment]
An example of how a bug didn't get into a release by testing prereleases/snapshots :)

https://github.com/nemtech/nem2-sdk-typescript-javascript/issues/458

Thanks Wayon
