### ISSUE TITLE
Creating an account will generate a bug

### ISSUE THREAD

**Issue by NemTechCD** [nemtech/nem2-sdk-java#27]
public KeyPair generateKeyPair() {
        final byte[] seed = new byte[32];
        this.random.nextBytes(seed);
        
        //in this line； Sometimes a 66-bit key is generated.
        final PrivateKey privateKey = new PrivateKey(ArrayUtils.toBigInteger(seed));

        return new KeyPair(privateKey, CryptoEngines.ed25519Engine());
    }

**Comment by NemTechCD** [comment]
new PrivateKey(ArrayUtils.toBigInteger(seed));

**Comment by fullcircle23** [comment]
Merged to cow-base/master and closed.
