### ISSUE TITLE
Does the previous faltbuffers continue to be used, or switch to catbuffer?

### ISSUE THREAD

**Issue by NemTechCD** [nemtech/nem2-sdk-java#37]
1. Expected behavior and actual behavior.

2. Steps to reproduce the problem.

3. Specifications like the version of the project, operating system, or hardware.

**Comment by fullcircle23** [comment]
Switching. Catbuffer will replace Flatbuffer.

**Comment by fullcircle23** [comment]
If you have further questions, you may also ask them in (nem2 slack channel)[https://nem2.slack.com] for quicker response. Questions related to Catbuffer and SDKs are generally asked in the #sig-api channel in (slack)[https://nem2.slack.com].
