### ISSUE TITLE
Is the XEM class not divided into 2 classes? I see js-sdk is doing this.

### ISSUE THREAD

**Issue by NemTechCD** [nemtech/nem2-sdk-java#38]
1. Expected behavior and actual behavior.

2. Steps to reproduce the problem.

3. Specifications like the version of the project, operating system, or hardware.

**Comment by fullcircle23** [comment]
Just as in js-sdk, XEM class will be divided into 2 classes in java-sdk.

**Comment by fullcircle23** [comment]
If you have further questions, you may also ask them in (nem2 slack channel)[https://nem2.slack.com] for quicker response. Questions related to Catbuffer and SDKs are generally asked in the #sig-api channel in (slack)[https://nem2.slack.com].
