### ISSUE TITLE
bug/ java.lang.NegativeArraySizeException

### ISSUE THREAD

**Issue by NemTechCN** [nemtech/nem2-sdk-java#42]
public SignedTransaction signWith(Account account) {

        Signer signer = new Signer(account.getKeyPair());
        byte[] bytes = this.generateBytes();
        byte[] signingBytes = new byte[bytes.length - 100];
        System.arraycopy(bytes, 100, signingBytes, 0, bytes.length - 100);
        Signature signature = signer.sign(signingBytes);

        byte[] payload = new byte[bytes.length];
        System.arraycopy(bytes, 0, payload, 0, 4); // Size
        System.arraycopy(signature.getBytes(), 0, payload, 4, signature.getBytes().length); // Signature
        System.arraycopy(account.getKeyPair().getPublicKey().getRaw(), 0, payload, 64 + 4, account.getKeyPair().getPublicKey().getRaw().length); // Signer
        System.arraycopy(bytes, 100, payload, 100, bytes.length - 100);

        String hash = Transaction.createTransactionHash(Hex.toHexString(payload));
        return new SignedTransaction(Hex.toHexString(payload).toUpperCase(), hash, type);
    }
 byte[] bytes = this.generateBytes();
 byte[] signingBytes = new byte[bytes.length - 100];
If you generate a byte array less than 100  An exception will occur

**Comment by fullcircle23** [comment]
@NemTechCD Thank you for reporting this issue.

**Comment by fboucquez** [comment]
Hi @NemTechCN, we have released a new version, 0.14.0. Do you still have the same problem? Which type of transaction were you trying to sign?

**Comment by fboucquez** [comment]
Hi @NemTechCN

I'm closing this issue. If you have any other problem please report it. 

Cheers
Fernando
