### ISSUE TITLE
Audit Merkle Proofs

### ISSUE THREAD

**Issue by evias** [nemtech/nem2-sdk-java#47]
Trees stored per block:

Transactions
State tree (merkle path not implemented in REST)
Receipts
Check if a transaction is included in a block

blockchainHttp
    .getTransactionMerkleAuditProof(height: uint, hash: string)
    .subscribe( merklePath => {    
        // Returns Observable<MerkleAuditProof>   
        console.log(merklePath.isConsistent()););
     }
Check if a receipt is included in a block

blockchainHttp
    .getReceiptMerkleAuditProof(height: uint, hash: string)
    .subscribe( merklePath => {    
        // Returns Observable<MerkleAuditProof>   
        console.log(merklePath.isConsistent()););
     }

**Comment by fboucquez** [comment]
Implemented in 0.14.0
