### ISSUE TITLE
Account Properties

### ISSUE THREAD

**Issue by evias** [nemtech/nem2-sdk-java#49]
Account Filter docs: https://nemtech.github.io/concepts/account-filter.html

Set account filters
const addressFilterExample = Filter.createForAddress(
    PropertyModificationType.Add, // Options: Add, Remove
    address
);

const mosaicFilterExample = Filter.createForMosaic(
    PropertyModificationType.Add, 
    mosaicId
);

const mosaicFilterExample = Filter.createForEntityType(
    PropertyModificationType.Add, 
    TransactionType.TRANSFER
);

AccountPropertiesTransaction.create(
    Deadline.create(),
    PropertyType.BlockAddress, // Allow(Block)Address, Allow(Block)Mosaic, Allow(Block)EntityType
    [addressFilterExample],
    NetworkType.MIJIN_TEST);
Get account properties from an account
accountHttp.getProperties(publicAccount: PublicAccount, queryParams: QueryParams): Observable<AccountProperties[]>

--

Please have a look at the PR in the nem2-sdk-typescript-javascript project to get an idea of how this can be integrated.

**Comment by fullcircle23** [comment]
Completed domain model object and unit testing.
Commit url: https://github.com/nemtech/nem2-sdk-java/commit/0ec85b65e4b4b041368f40c429e736591d6cd7e4

**Comment by fullcircle23** [comment]
Raised following question in Slack #sig-api:

I find the Account Properties documentation, REST API reference, and TS SDK to be confusing and/or not aligned. For e.g. AccountPropertiesAddressTransaction don't correspond in the above. Another example, AccountProperty in TS SDK has aPropertyType and values (object[]) but isn't clear what are valid values.

It seems to me that 'values' can be a list of one of the following objects but I'm not 100% sure as the docs doesn't clearly define this and the unit test cases in TS SDK includes other object types in 'values':
- Address
- MosaicId
- EntityType

Temporarily stopping work on this until above question is answered. Thanks.
