### ISSUE TITLE
Same PrivateKey Different Address/Public Keys btw Nem2 and Nem

### ISSUE THREAD

**Issue by denizdurmus** [nemtech/nem2-sdk-java#5]
Yesterday I have created a test account as follows, by using the SDK

```java
Account account = Account.createFromPrivateKey(KeyPair.random(new Ed25519CryptoEngine()).getPrivateKey().toString(),NetworkType.TEST_NET);
```

And the created account details are as follows:

```text
Address : TBHBKP-QVQSO2-4VMJ3U-7MVSVO-FINF4J-TLERD5-ULYA
Private Key : 10BF65C11EC3F0D40A677818001CE01ABCC12A2337715A79F60CF67A0E54B1AD
Public Key : 64BB9E8B02D4BD6B0BEB3F98D874F8251F381CA1F605E76F894267AB1DE460A7
```

Then I have used the address in the forum to get some testnet tokens, however,  [the address appeared to be invalid](
https://forum.nem.io/t/paste-you-address-here-for-beta-nem-testnet-xem/829/1241)

Then by using the private key created above, I have tried to create account with the current version on typescript:

```javascript
let account = Account.createWithPrivateKey("10BF65C11EC3F0D40A677818001CE01ABCC12A2337715A79F60CF67A0E54B1AD");
```

And the result is:

```text
"address":"TA7DFT-Z7LLXP-VI54WA-EB7HWA-3GBJSW-VNDMQV-DGGJ"
"privateKey":"10BF65C11EC3F0D40A677818001CE01ABCC12A2337715A79F60CF67A0E54B1AD"
"publicKey":"fbbc7c6c246d4f1eba772ef5a28fe8aa43f44d007e2444aaecd55d8ea2ec53b4"
```

Then I have tried to the other way around (Generating account on current version and by using its key in the nem2 sdk)
```javascript
let account = Account.generateAccount("wallet1", "pass", NetworkTypes.TEST_NET)
```

created account details:
```text
"address":"TAJNNU-6HPTIH-DSMLWC-Y6DFVW-5C62LA-WNI4NL-PRYX"
"privateKey":"705F95713D0AAEAF997F5AABD4CC82E3A94C22D76C6FED1FB0AEA3BE9ABA86D0"
"publicKey":"9fc404ea056f2508798a747effcb6e312d417b429b67bc0e17affcacbc1c5c12"
```

And from the java sdk, the result is 
```java
Account account = Account.createFromPrivateKey("705F95713D0AAEAF997F5AABD4CC82E3A94C22D76C6FED1FB0AEA3BE9ABA86D0",NetworkType.TEST_NET);
```
```text
Address : TC5NFE-O2TLVB-LA47NF-YVZMM7-3FBMTF-WD7TNZ-YSTT
Private Key : 705F95713D0AAEAF997F5AABD4CC82E3A94C22D76C6FED1FB0AEA3BE9ABA86D0
Public Key : D01C78152C0342C52A947A1E09E4406A427A7E3EECD3CC084E1C4C7258E09F47
```

Is this something intended that two versions are not returning the same address for the same private key?

**Comment by kodty** [comment]
In nem 1 nis, Keccak hash function is used during account derivation from a private key, and also the private key bytes get reversed. In nis 2 catapult, regular Sha-3 is used. So that's why you are getting different accounts between nis 1 and nis 2.

**Comment by denizdurmus** [comment]
thanks for the explanation

so what will happen to the addresses on nis1 once nis2 becomes standard? 
and another question (actually this is where i have started checking out the difference), for the example here https://nemtech.github.io/guides/transaction.html#using-secret-lock-for-atomic-cross-chain-swap-transactions it will only work nis2-nis2 chains or it can work for nis2-nis1 as well?

**Comment by kodty** [comment]
Possibly Keccak will be used on public chain to allow for compatibility with nis1 addresses, while Sha-3 is used on private chains. Unsure though what the devs plan to do.

Nis 1 doesn't support atomic swaps in this way, so swaps between nis 1 and 2 wouldn't be possible. Technically you can use it with bitcoin or any other chain that has implemented the [swap standard](https://en.bitcoin.it/wiki/Atomic_cross-chain_trading) used in for bitcoin. Maybe someone will do this for nis 1, but it wouldn't really make sense to do so.

**Comment by aleixmorgadas** [comment]
as @kodty said, the public network uses Keccak and private SHA3. The SDK will support both hash functions to use them depending on the network.

So, the current key generation behaviour when you use `TEST_NET` or `MAIN_NET` networks will be changed in the future to have backwards compatibility.
