### ISSUE TITLE
Fees changes with maxFee

### ISSUE THREAD

**Issue by evias** [nemtech/nem2-sdk-java#50]
https://nemtech.github.io/concepts/transaction.html#fees

Include maxFee field in the transaction.

TransferTransaction.create(
    Deadline.create(),  
    Address.createFromRawAddress('S..4'),
    [new Mosaic( Alias.create('alice.token'), UInt64.fromUint(10)],
    PlainMessage.create('Welcome To NEM'),
    NetworkType.MIJIN_TEST,
    NetworkCurrencyMosaic.createRelative(10), // maxFee);

--

maxFee field should be optional and take [0, 0] as a default.

**Comment by fullcircle23** [comment]
Working on this.

**Comment by fullcircle23** [comment]
Link to same enhancement in TS SDK: https://github.com/nemtech/nem2-sdk-typescript-javascript/issues/53

**Comment by fboucquez** [comment]
We aware that maxFee has been changed to max_fee in the last open api specification

**Comment by fboucquez** [comment]
maxFee is an optional field you set when creating the transaction factory now.
