### ISSUE TITLE
expose serialization

### ISSUE THREAD

**Issue by evias** [nemtech/nem2-sdk-java#57]
The NEM-SDK has a class [TransactionMapping ](https://github.com/nemtech/nem2-sdk-java/blob/450676210c5a75f4624fc3bee7bbde96740109d1/src/main/java/io/nem/sdk/infrastructure/TransactionMapping.java) to map JSON transactions into models.

It can be [useful](https://github.com/nemtech/NIP/issues/6) for advanced users to make use the json mapping, and as well get transactions in serialized form. This table gathers the functions that each transaction model could implement.

<table>
  <tr>
   <td><strong>Function</strong>
   </td>
   <td><strong>Description</strong>
   </td>
  </tr>
  <tr>
   <td>serialize():string
   </td>
   <td>Serializes a transaction model into binary (unsigned payload)
   </td>
  </tr>
  <tr>
   <td>toDTO():json	
   </td>
   <td>Serializes a transaction model into JSON
   </td>
  </tr>
  <tr>
   <td>createFromPayload(data:string):Transaction
   </td>
   <td>Reads the unsigned payload and creates a Transaction.
   </td>
  </tr>
  <tr>
   <td>createFromDTO(data:json):Transaction
   </td>
   <td>Reads from JSON and creates a Transaction.
   </td>
  </tr>
</table>

For function createFromPayload(data:string):Transaction, refer to issue #123.

**Comment by fboucquez** [comment]
The from/to JSON is done. From Payload is missing and being handled in https://github.com/nemtech/nem2-sdk-java/issues/123
