### ISSUE TITLE
Publish sdk artifact to public repository

### ISSUE THREAD

**Issue by fullcircle23** [nemtech/nem2-sdk-java#82]
Fix the build process to publish java sdk artifact to maven public repository

Write instruction doc

**Comment by fboucquez** [comment]
https://dzone.com/articles/publish-your-artifacts-to-maven-central
https://dzone.com/articles/deploy-maven-central

**Comment by fullcircle23** [comment]
> https://dzone.com/articles/publish-your-artifacts-to-maven-central
> https://dzone.com/articles/deploy-maven-central
> https://issues.sonatype.org/browse/OSSRH-38683

Thanks @fboucquez. I've seen those.. waiting for @dgarcia360 to provide the account which can access the Jira / java sdk artifact that had been uploaded to sonatype previously.

**Comment by rg911** [comment]
> > https://dzone.com/articles/publish-your-artifacts-to-maven-central
> > https://dzone.com/articles/deploy-maven-central
> > https://issues.sonatype.org/browse/OSSRH-38683
> 
> Thanks @fboucquez. I've seen those.. waiting for @dgarcia360 to provide the account which can access the Jira / java sdk artifact that had been uploaded to sonatype previously.

let move this kind of conversation into private channels. 👍

**Comment by fboucquez** [comment]
How to deploy and sign from Travis.
https://github.com/stefanbirkner/travis-deploy-to-maven-central
