### ISSUE TITLE
Review javadoc comments

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-sdk-java#84]
**1. Expected behavior and actual behavior.**

Javadoc should compile without warnings or errors. Most of the errors are caused by:

* Function parameters not documented.
* Function returns not documented.
* Invalid tags.

> 100 errors
> 100 warnings
> 
> FAILURE: Build failed with an exception.

**2. Steps to reproduce the problem.**

Run ``./gradlew javadoc``

**3. Specifications like the version of the project, operating system, or hardware.**
* Windows
* Java 8

**Comment by dgarcia360** [comment]
Javadoc can be added as a travis script to ensure that every branch that is merged against master has every function properly documented.

**Comment by fboucquez** [comment]
Having the same problem. I've deactivated build fail on Javadoc error in gradle locally to continue my testing. 

The main blocking error is unknown tag: http.response.details

**Comment by fboucquez** [comment]
Javadocs should be published automatically by Travis to github pages like the javascript SDK.

https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/master/.travis.yml#L13
https://nemtech.github.io/nem2-sdk-typescript-javascript/ 

We need to consider how the different modules' JavaDoc, including the generated artifacts, are published into Github pages, define the folder structure for multi modules in pages.

**Comment by fboucquez** [comment]
javadoc is published automatically from travis
