### ISSUE TITLE
Infrastructure refactoring

### ISSUE THREAD

**Issue by fboucquez** [nemtech/nem2-sdk-java#85]
@rg911 and @fullcircle23  from the NEM Java SDK team and I discussed the current problems the project structure faces:

1. OpenAPI Generated code is generated inside written code packages making hard to tell which files are which. Devs may modify generated code making hard to regenerate in case the open API/Swagger definition changes.  Generated code should be in at least its own package, much better if it has its own Maven/Gradle project and artifact.
2. Generated code is built alongside the SDK manual code when the generated API changes much less often.  Javadoc task complains about the generated code having unknown tags. If the code is in its own project, the SDK won't need to build it or generate the Javadoc. https://github.com/nemtech/nem2-sdk-java/issues/84
3. Generated code is tailored to gson and okhttp when the code clients are using Jackson2 and Vertex. SDK clients would depend on both.
4. The generated code structure is pretty much the same between the different target flavors (jersey2, vertx, okhttp-gson) for both generated DTOs and generated clients. It should be easy to migrate from one to the other. Then we can decide which one suits the community better. For example, okhttp is more android friendly than vertx. We may be able to support both if have the right abstractions. Example, having API project with interfaces (model and repositories), and different SDK implementation with the different dependencies https://github.com/nemtech/nem2-sdk-java/issues/8
5. Current clients are manually written using vertex (AccountHttp for example) and the generated clients are ignored. The clients should use the generated clients to save a lot of boilerplate and to (possible) swap between one client lib to another. If the generated clients have bugs, it may be harder to fix as the generated clients cannot be touched. It may be possible to configure the generated client (like Jackson ignore unknown properties https://github.com/nemtech/nem2-sdk-java/issues/81 , https://github.com/nemtech/nem2-sdk-java/issues/9), change the generator options or extend them to solve these possible issues.
6. JSON parsing and rendering should be abstracted away so the libs can be swapped between GSON and Jackson2 easily. The generated client will do most of the JSON processing anyway.
7. Repository interfaces should be moved from io.nem.sdk.infrastructure to io.nem.sdk.api package. They should not be in the same package than the implementation (we may have different implementation for different libraries). If we plan to support multiple lib implementations (like vertex, jersey or okhttp), the repository and model must have their own API project/artifact.  A RepositryFactory interface should be created so we can abstract away how each repository is created (as we may have multiple implementations, one per each lib). 

Current repository interfaces use io.reactivex.Observable. When refactoring to use the OpenAPI generated client, we sure that the calls are non-blocking and they perform well without losing the reactiveness!. Should we void using reactivex interface and start using Java interfaces like Future? Is there enough benefits in the reactivex lib to tight the API to this lib? Is reactivex android friendly?

Before creating new projects, we need to solve how the artifacts will be deployed into maven central https://github.com/nemtech/nem2-sdk-java/issues/82. Then the SDK will download the dependencies automatically. 
Having separate projects for the generated code and for the APIs will be a future improvement.

Some of the items above will have their own ticket in Github. 

https://openapi-generator.tech/docs/generators/java
https://github.com/nemtech/nem2-docs/tree/master/source/resources/collections

I'll fork the repo and work on the structure refactoring.

**Comment by fboucquez** [comment]
These are the forks:

https://github.com/fboucquez/nem2-sdk-openapi-generator
https://github.com/fboucquez/nem2-sdk-java

**Comment by evias** [comment]
i would mark that this is `java` only and may need a different naming:

`nem2-sdk-java-autogen` for example, or `nem2-sdk-java-openapi`

Even better would be a more complete package with all required languages. But this could become cumbersome in deployment (general `nem2-sdk-openapi` with all languages we support.)

**Comment by fboucquez** [comment]
Thanks @evias for the feedback. 

I agree that generating clients for other languages is cumbersome. We can always have a different repo with a different set of tools for generating, building and deploying another language (typescript would be a mix of open-api-generator, npm, ts compiler, etc)

This my proposal for the project and folder structure of the Java related libraries. 

![image](https://user-images.githubusercontent.com/5390558/62324570-246bdf00-b4aa-11e9-8c20-f38ced28ee56.png)

**Comment by fboucquez** [comment]
@rg911 @fullcircle23, Are you happy to close this issue?
