### ISSUE TITLE
Enable Sonar(cloud) and revisit existing issues

### ISSUE THREAD

**Issue by fboucquez** [nemtech/nem2-sdk-java#99]
I've executed sonar in the old single module master.  The report is the following:

https://sonarcloud.io/dashboard?id=fboucquez_nem2-sdk-java

I reckon it worth checking out the issues and fix them as necessary. 

This task would be to enable an official Sonar, upgrade Travis and Gradle in the new multimodule master. Once set, fix the high-risk issues/problems.

**Comment by fboucquez** [comment]
I've re-executed sonar in the new master.  It's in the same repo

https://sonarcloud.io/dashboard?id=fboucquez_nem2-sdk-java

At the moment, there are 258 possible issues in catbuffer generated code

https://sonarcloud.io/project/issues?directories=sdk-core%2Fsrc%2Fmain%2Fjava%2Fio%2Fnem%2Fcatapult%2Fbuilders&id=fboucquez_nem2-sdk-java&resolved=false

Should we fix the generator to make sonar happier? Should we exclude catbuffer from sonar checking? We cannot manually fix the generated code.

**Comment by rg911** [comment]
@Wayonb

**Comment by fboucquez** [comment]
I have disabled catbuffer folder and fixed many of the current issues in a branch.

https://github.com/fboucquez/nem2-sdk-java/tree/task/g99_enable_sonar
https://github.com/fboucquez/nem2-sdk-java/tree/task/g99_sonar_issues

A related issue that can affect how we can showcase "sonar-fixes" branches.

https://community.sonarsource.com/t/view-all-issues-in-a-branch-not-only-new-ones/12172

The branch report:

https://sonarcloud.io/dashboard?branch=task%2Fg99_sonar_issues&id=fboucquez_nem2-sdk-java

Only shows the new issues, it doesn't show the 100s of fixed issues.

We wouldn't have many of these branches as most of them will be features branches. Then sonar will show how badly a branch affects master.

**Comment by fboucquez** [comment]
Fixed
